# Site settings
title: An amazing book store
email: pete@pete.com
description: "Bla Bla Bla Bla"
baseurl: ""
url: "http://localhost:4000"
github_username:

# Build settings
markdown: kramdown
permalink: pretty
include: ['_pages']
kramdown:
  input: GFM

theme: jekyll-theme-minimal